//! A QR code, drawn here rather than fetched from somebody else.
//!
//! The share bar's WeChat button showed a QR generated by `api.qrserver.com`.
//! Three things wrong with that, in rising order of seriousness:
//!
//! 1. It is a request to a third party on every page view, on a page whose
//!    whole latency budget is already spent on a bad uplink.
//! 2. It hands that third party the URL of every story any reader considers
//!    sharing. Readers did not agree to that, and it is not ours to give.
//! 3. **It does not work for the people it is for.** The QR exists so a
//!    desktop reader can scan the page into WeChat. WeChat's users are largely
//!    in mainland China, where `api.qrserver.com` is unreliable — so the one
//!    audience the feature serves is the one most likely to see a broken image.
//!
//! A QR code is a few hundred bytes of arithmetic. Encoding it here makes it
//! inline SVG in the HTML: no request, no dependency, no leak, and it renders
//! offline. It is also WASM-safe, so hydration produces the same markup the
//! server sent instead of tearing it down and rebuilding it.

use qrcode::{types::Color, QrCode};

/// Draw `data` as a self-contained SVG QR code, or `None` if it will not fit.
///
/// Returns markup rather than an element so the caller can drop it in with
/// `inner_html` on either side of the WASM boundary.
///
/// The modules are emitted as a single `<path>` rather than one `<rect>` each.
/// A URL-sized code is 37×37, and 500-odd rect elements is 20 KB of markup and
/// 500 nodes for the browser to lay out; the same picture as one path is under
/// 4 KB and one node.
pub fn svg(data: &str, px: u32) -> Option<String> {
    let code = QrCode::new(data.as_bytes()).ok()?;
    let modules = code.width();
    let colors = code.to_colors();

    // A quiet zone is part of the specification, not decoration: without it
    // scanners cannot find the code's edges against the surrounding page. Four
    // modules is the minimum the spec allows.
    const QUIET: usize = 4;
    let side = modules + QUIET * 2;

    let mut path = String::with_capacity(modules * modules * 8);
    for y in 0..modules {
        // Runs of adjacent dark modules become one wide rectangle instead of
        // several squares, which roughly halves the path again on the timing
        // patterns and any solid block.
        let mut x = 0;
        while x < modules {
            if colors[y * modules + x] != Color::Dark {
                x += 1;
                continue;
            }
            let start = x;
            while x < modules && colors[y * modules + x] == Color::Dark {
                x += 1;
            }
            let run = x - start;
            path.push_str(&format!(
                "M{} {}h{}v1h-{}z",
                start + QUIET,
                y + QUIET,
                run,
                run
            ));
        }
    }

    Some(format!(
        // `shape-rendering=crispEdges` matters at small sizes: with the default
        // antialiasing the module edges blur into their neighbours and phone
        // cameras start failing to decode it.
        "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 {side} {side}\" \
         width=\"{px}\" height=\"{px}\" shape-rendering=\"crispEdges\" \
         role=\"img\" aria-label=\"QR code for this page\">\
         <rect width=\"{side}\" height=\"{side}\" fill=\"#ffffff\"/>\
         <path d=\"{path}\" fill=\"#0B0D10\"/></svg>"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn encodes_a_story_url() {
        let s = svg(
            "https://victoriapark.io/story/how-china-will-win-the-ai-race",
            180,
        )
        .unwrap();
        assert!(s.starts_with("<svg"));
        assert!(s.contains("viewBox"));
        // Some modules are dark, i.e. we drew an actual code and not a blank.
        assert!(s.contains("<path d=\"M"));
    }

    #[test]
    fn stays_small() {
        // The reason for run-length encoding the path. A per-module <rect>
        // rendering of the same URL is around 20 KB.
        let s = svg(
            "https://victoriapark.io/story/some-reasonably-long-story-slug",
            180,
        )
        .unwrap();
        assert!(s.len() < 6_000, "QR markup grew to {} bytes", s.len());
    }

    #[test]
    fn quiet_zone_is_present() {
        // Four clear modules on every side, or scanners cannot find the edges.
        let s = svg("https://victoriapark.io/", 180).unwrap();
        let code = QrCode::new("https://victoriapark.io/".as_bytes()).unwrap();
        let side = code.width() + 8;
        assert!(s.contains(&format!("viewBox=\"0 0 {side} {side}\"")));
    }

    #[test]
    fn refuses_what_will_not_fit() {
        // Better a missing QR than one that silently encodes a truncated URL.
        assert!(svg(&"x".repeat(10_000), 180).is_none());
    }
}
