//! What a share card says when the newsroom has not written a standfirst yet.
//!
//! 395 of 1,696 published stories — and 71 of the last two days' — have neither
//! an article dek nor a summary. Every one of those shared as a headline and an
//! empty space, which is the difference between a card someone opens and a card
//! they scroll past.
//!
//! The gap is structural rather than a bug: a summary costs tokens, the daily
//! allowance buys about a hundred, and the Wire deliberately carries more items
//! than that. Waiting for the model is not an option for the newest story on
//! the site, which is exactly the one being shared.
//!
//! So the fallback is built from what the newsroom already knows for certain —
//! who reported it, how many independently, and whether the Skein has been over
//! it. That is not filler: **it is the thing VictoriaPark has that an aggregator
//! does not**, and on a story with four outlets behind it, it is a better
//! reason to click than a paraphrase of the headline would be.
//!
//! Nothing here is generated by a model or inferred. If a fact is not known it
//! is left out, and the line stays shorter.

/// A standfirst assembled from the coverage itself.
///
/// `outlets` is ordered seed-first — the outlet that reported it first leads,
/// which is also the attribution a reader most wants.
///
/// Only ever states what is on record:
/// - "Reported by Tom's Hardware." — one source
/// - "Reported by Decrypt and CoinDesk." — two
/// - "Reported by Decrypt, CoinDesk and 3 other outlets." — more
///
/// then, when there is corroboration or analysis to point at, what the story
/// page adds to that.
pub fn coverage_line(outlets: &[String], has_analysis: bool) -> String {
    let named: Vec<&str> = outlets
        .iter()
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .collect();

    let who = match named.len() {
        0 => String::new(),
        1 => format!("Reported by {}.", named[0]),
        2 => format!("Reported by {} and {}.", named[0], named[1]),
        3 => format!("Reported by {}, {} and {}.", named[0], named[1], named[2]),
        n => format!(
            "Reported by {}, {} and {} other outlets.",
            named[0],
            named[1],
            n - 2
        ),
    };

    // What the page offers beyond the link, stated only where it is true.
    let adds = match (named.len() >= 2, has_analysis) {
        (true, true) => {
            "Every claim is shown with the outlets that confirm it, alongside VictoriaPark's analysis."
        }
        (true, false) => "Every claim is shown with the outlets that confirm it.",
        (false, true) => "Read with VictoriaPark's analysis of what it means.",
        (false, false) => "Every claim is shown with the source behind it.",
    };

    if who.is_empty() {
        return adds.to_string();
    }
    format!("{who} {adds}")
}

/// The description for a story, preferring what was actually written.
///
/// A dek written by the Copydesk always wins; the summary next; the coverage
/// line only when there is nothing else. Ordering it this way means improving
/// the pipeline automatically improves the cards, with no second place to
/// change.
pub fn description(dek: &str, summary: &str, outlets: &[String], has_analysis: bool) -> String {
    for written in [dek, summary] {
        let t = written.trim();
        if !t.is_empty() {
            return t.to_string();
        }
    }
    coverage_line(outlets, has_analysis)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(names: &[&str]) -> Vec<String> {
        names.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn what_was_written_always_wins() {
        let d = description(
            "The regulator said it would act alone if the bill stalls.",
            "ignored",
            &v(&["Decrypt"]),
            true,
        );
        assert_eq!(
            d,
            "The regulator said it would act alone if the bill stalls."
        );
    }

    #[test]
    fn the_summary_is_the_second_choice() {
        let d = description("   ", "A summary.", &v(&["Decrypt"]), false);
        assert_eq!(d, "A summary.");
    }

    #[test]
    fn a_card_is_never_blank() {
        // The whole point: 395 stories were sharing with an empty description.
        for outlets in [v(&[]), v(&["Decrypt"]), v(&["Decrypt", "CoinDesk"])] {
            for analysis in [true, false] {
                let d = description("", "", &outlets, analysis);
                assert!(!d.trim().is_empty(), "blank for {outlets:?}/{analysis}");
            }
        }
    }

    #[test]
    fn outlets_are_named_the_way_a_person_would() {
        assert!(coverage_line(&v(&["Tom's Hardware"]), false)
            .starts_with("Reported by Tom's Hardware."));
        assert!(coverage_line(&v(&["Decrypt", "CoinDesk"]), false)
            .starts_with("Reported by Decrypt and CoinDesk."));
        assert!(
            coverage_line(&v(&["Decrypt", "CoinDesk", "The Block"]), false)
                .starts_with("Reported by Decrypt, CoinDesk and The Block.")
        );
        assert!(
            coverage_line(
                &v(&["Decrypt", "CoinDesk", "The Block", "DL News", "Blockworks"]),
                false
            )
            .starts_with("Reported by Decrypt, CoinDesk and 3 other outlets."),
            "{}",
            coverage_line(
                &v(&["Decrypt", "CoinDesk", "The Block", "DL News", "Blockworks"]),
                false
            )
        );
    }

    #[test]
    fn it_never_claims_corroboration_it_does_not_have() {
        let one = coverage_line(&v(&["Decrypt"]), false);
        assert!(!one.contains("outlets that confirm"), "{one}");
        assert!(one.contains("the source behind it"), "{one}");

        let two = coverage_line(&v(&["Decrypt", "CoinDesk"]), false);
        assert!(two.contains("outlets that confirm it"), "{two}");
    }

    #[test]
    fn analysis_is_mentioned_only_when_there_is_one() {
        assert!(!coverage_line(&v(&["Decrypt"]), false).contains("analysis"));
        assert!(coverage_line(&v(&["Decrypt"]), true).contains("analysis"));
    }

    #[test]
    fn empty_outlet_names_are_not_rendered_as_gaps() {
        // A source with a blank name would otherwise produce "Reported by ."
        let d = coverage_line(&v(&["", "  "]), false);
        assert!(!d.contains("Reported by"), "{d}");
        assert!(!d.trim().is_empty());
    }

    #[test]
    fn it_stays_inside_what_a_preview_shows() {
        // WeChat renders roughly two lines; anything past ~200 characters is
        // cut anyway, and a sentence severed mid-clause reads worse than a
        // shorter one.
        let longest = coverage_line(
            &v(&[
                "Bitcoin Magazine",
                "Cointelegraph",
                "The Defiant",
                "DL News",
            ]),
            true,
        );
        assert!(longest.len() <= 200, "{} chars: {longest}", longest.len());
    }
}

/// Whether a piece of generated copy is the model declining rather than writing.
///
/// A small model asked to name a topic it cannot see enough of does not return
/// an error — it writes "No story", "Hold: insufficient coverage", "CPI Coverage
/// Unverified". Stored unchecked, those became **seven of the twelve special
/// topics on the live front page**, each proudly labelled "5 outlets".
///
/// The tell is that the text describes the *act of reporting* rather than the
/// subject: a refusal talks about coverage, availability and viability, where a
/// headline talks about the thing that happened. Matching on that is crude and
/// catches the whole family, which a list of exact strings would not.
///
/// Deliberately narrow at the front: only copy that *opens* this way is
/// rejected. "No viable story" is a refusal; "No viable path to a Senate vote"
/// is a headline, and the difference is what follows.
pub fn reads_as_a_refusal(text: &str) -> bool {
    let t = text.trim().to_lowercase();
    if t.is_empty() {
        return true;
    }
    const OPENERS: &[&str] = &[
        "no story",
        "no viable",
        "no significant",
        "no clear",
        "no coverage",
        "no ",
        "none ",
        "hold",
        "insufficient",
        "unable to",
        "cannot ",
        "not enough",
        "n/a",
        "unknown",
        "pending",
        "tbd",
        "placeholder",
    ];
    if OPENERS.iter().any(|p| t.starts_with(p)) {
        return true;
    }
    // Or ends by admitting the gap: "Kalshi coverage pending",
    // "CPI Coverage Unverified", "Goldman Sachs — insufficient coverage".
    const ADMISSIONS: &[&str] = &[
        "coverage pending",
        "coverage unverified",
        "insufficient coverage",
        "not available",
        "no data",
        "awaiting",
    ];
    ADMISSIONS.iter().any(|p| t.contains(p))
}

#[cfg(test)]
mod refusal_tests {
    use super::*;

    /// Every one of these was on the live front page as a "special topic".
    #[test]
    fn the_refusals_that_shipped_are_caught() {
        for s in [
            "No SEC story available",
            "No story",
            "No viable story",
            "Hold",
            "Hold: insufficient coverage",
            "Kalshi coverage pending",
            "CPI Coverage Unverified",
            "",
            "   ",
        ] {
            assert!(reads_as_a_refusal(s), "missed: {s:?}");
        }
    }

    /// And real headlines survive, including ones that start with "No".
    #[test]
    fn real_copy_is_not_mistaken_for_a_refusal() {
        for s in [
            "Clarity Act Set for September Senate Vote",
            "Tether Completes First Full Audit",
            "Trump Media Pulls Back From Crypto",
            "Harmony ONE Price Falls 26% After Minting Attack",
            "Nobody expected the Fed to move this week",
            "Nvidia earnings beat expectations",
        ] {
            assert!(!reads_as_a_refusal(s), "false positive: {s:?}");
        }
    }
}
